USE DbHospedajeNeydita
GO

CREATE FUNCTION MesActual(@fecha DATE)
RETURNS INT 
AS
BEGIN
	DECLARE @mes INT = MONTH(@fecha)
	RETURN @mes
END
GO

SELECT dbo.MesActual(GETDATE()) AS [MES ACTUAL]
GO

CREATE PROCEDURE CLIENTES_CUMPLEAÑEROS
AS
BEGIN
	DECLARE @mesactual INT = dbo.MesActual(GETDATE())
	IF EXISTS(SELECT * FROM Persona p WHERE MONTH(p.DNacimiento) = @mesactual)
	BEGIN
		SELECT p.CPersona AS [Código], p.NPersona AS [Nombre del Cliente]
		FROM Persona p
		PRINT 'EL EQUIPO DE MARKETING LES ENVIARÁ UN CORREO OFRECIÉNDOLES UN DESCUENTO'
	END
	ELSE
		PRINT 'NINGÚN CLIENTE CUMPLE AÑOS ESTE MES'
END
GO

EXEC CLIENTES_CUMPLEAÑEROS 
GO
